### ISSUE TITLE
__pycache__

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc#509]
left all over

**Comment by arturum1** [comment]
Solved in commit https://github.com/arturum1/iob-lib/commit/b5e4829899924d75f41e445d495637af4b79eb62

**Comment by PedroAntunes178** [comment]
I had an easier solution:
```
$(BUILD_DIR): python_setup python-cache-clean

python_setup:
	./$(SETUP_PYTHON_FILENAME) $(SETUP_ARGS)
```

**Comment by arturum1** [comment]
That solution involves creating and deleting files while the one I proposed using the -B flag prevents creating the files altogether.
Also, that solution `$(BUILD_DIR): python_setup python-cache-clean` may not work well if python_setup fails midway because that will exit Make without calling python-cache-clean to clean the files.

**Comment by jjts** [comment]
It is always better to prevent garbage than to garbage collect later

**Comment by PedroAntunes178** [comment]
@jjts I believe this issue can be closed, since it was solved in the referenced PRs. (https://github.com/IObundle/iob-soc/pull/513 and https://github.com/IObundle/iob-lib/pull/416)
